/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_illinios_cs241_webcam_WebcamMainActivity */

#ifndef _Included_edu_illinios_cs241_webcam_WebcamMainActivity
#define _Included_edu_illinios_cs241_webcam_WebcamMainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_illinios_cs241_webcam_WebcamMainActivity
 * Method:    nativeStartServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_illinios_cs241_webcam_WebcamMainActivity_nativeStartServer
  (JNIEnv *, jobject);

/*
 * Class:     edu_illinios_cs241_webcam_WebcamMainActivity
 * Method:    nativeStopServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_illinios_cs241_webcam_WebcamMainActivity_nativeStopServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
